import type { Metadata } from "next";
import { pageMetadata } from "@/lib/seo";
import PageShell from "@/components/PageShell";

export const metadata: Metadata = pageMetadata({ title: "Gizlilik ve KVKK Aydınlatma Metni", description: "sezginildes.com üzerinden paylaşılan kişisel verilerin işlenmesine ilişkin aydınlatma metni.", path: "/gizlilik" });

const sections: Array<{ heading: string; paragraphs: string[] }> = [
  { heading: "Veri sorumlusu", paragraphs: ["Bu aydınlatma metni, 6698 sayılı Kişisel Verilerin Korunması Kanunu (KVKK) kapsamında, sezginildes.com sitesi üzerinden benimle iletişime geçen kişilerin kişisel verilerinin nasıl işlendiğini açıklamak amacıyla veri sorumlusu sıfatıyla Sezgin İldeş tarafından hazırlanmıştır."] },
  { heading: "Hangi veriler, hangi kanallardan işlenir?", paragraphs: ["WhatsApp veya e-posta üzerinden iletişime geçtiğinizde: ad-soyad, telefon numarası veya e-posta adresi ile mesajınızda paylaşmayı tercih ettiğiniz bilgiler.", "Takvim üzerinden randevu planladığınızda: ad-soyad, e-posta adresi ve seçtiğiniz görüşme zamanı.", "E-posta bültenine kaydolduğunuzda: e-posta adresiniz ve verdiğiniz onayın kaydı.", "Site üzerinden bunların dışında bir kişisel veri toplanmaz; sitede üyelik sistemi bulunmaz."] },
  { heading: "İşleme amaçları ve hukuki sebepler", paragraphs: ["Kişisel verileriniz; taleplerinize yanıt verilmesi, görüşme ve randevu süreçlerinin planlanması, danışmanlık ve eğitim hizmetlerinin yürütülmesi, açık rızanız bulunması hâlinde e-posta bülteni gönderilmesi ve yasal yükümlülüklerin yerine getirilmesi amaçlarıyla işlenir.", "Bu işleme; KVKK madde 5 kapsamında açık rızanız, bir sözleşmenin kurulması veya ifası için gerekli olması, hukuki yükümlülüğün yerine getirilmesi ve temel hak ve özgürlüklerinize zarar vermemek kaydıyla meşru menfaat hukuki sebeplerine dayanır."] },
  { heading: "Görüşme içeriklerinin gizliliği", paragraphs: ["Danışmanlık görüşmelerinde paylaşılan bilgiler, mesleki etik ilkeler ve gizlilik esasıyla ele alınır; üçüncü kişilerle paylaşılmaz. Gizliliğin yasal sınırları ilk görüşmede açıkça konuşulur."] },
  { heading: "Verilerin aktarılması", paragraphs: ["İletişim ve randevu süreçlerinde WhatsApp (Meta), Google (e-posta), Calendly (randevu) ve sitenin barındırıldığı Vercel ile bülten kayıtlarının tutulacağı Supabase altyapısı kullanılır. Bu hizmet sağlayıcıların sunucuları yurt dışında bulunabilir; ilgili kanalı kullanarak iletişime geçtiğinizde verileriniz bu altyapılar üzerinden işlenir.", "Kişisel verileriniz bunun dışında hiçbir üçüncü kişiyle paylaşılmaz, satılmaz veya pazarlama amacıyla aktarılmaz."] },
  { heading: "Saklama süresi", paragraphs: ["Kişisel verileriniz, işleme amacının gerektirdiği süre ve ilgili mevzuatta öngörülen zamanaşımı süreleri boyunca saklanır. Bülten kaydınız, listeden ayrılma talebinize kadar tutulur; ayrılma talebiniz üzerine e-posta adresiniz listeden silinir."] },
  { heading: "KVKK kapsamındaki haklarınız", paragraphs: ["KVKK madde 11 uyarınca; kişisel verilerinizin işlenip işlenmediğini öğrenme, işlenmişse buna ilişkin bilgi talep etme, işleme amacını ve amacına uygun kullanılıp kullanılmadığını öğrenme, eksik veya yanlış işlenmişse düzeltilmesini isteme, silinmesini veya yok edilmesini talep etme ve işlenen verilerin münhasıran otomatik sistemlerle analiz edilmesi sonucu aleyhinize bir sonucun ortaya çıkmasına itiraz etme haklarına sahipsiniz.", "Bu haklarınıza ilişkin taleplerinizi sezgin.ildes@gmail.com adresine iletebilirsiniz; talebiniz en geç 30 gün içinde yanıtlanır."] },
];

export default function PrivacyPage() {
  return <PageShell><article className="shell max-w-4xl py-20 sm:py-28"><p className="eyebrow">GİZLİLİK</p><h1 className="display mt-5 text-4xl leading-[1.05] text-[#17324f] sm:text-5xl">KVKK Aydınlatma Metni</h1><p className="mt-6 max-w-2xl text-lg leading-8 text-slate-600">Bu sayfa, sezginildes.com üzerinden benimle iletişime geçtiğinizde kişisel verilerinizin nasıl işlendiğini açıklar.</p><div className="mt-14 space-y-12">{sections.map((section) => <section key={section.heading}><h2 className="text-2xl font-semibold text-[#17324f]">{section.heading}</h2><div className="mt-4 space-y-4">{section.paragraphs.map((text) => <p key={text} className="leading-8 text-slate-600">{text}</p>)}</div></section>)}</div><p className="mt-14 text-sm text-slate-500">Son güncelleme: Temmuz 2026</p></article></PageShell>;
}
