import Image from "next/image";
import Link from "next/link";
import PageShell from "@/components/PageShell";
import SectionHeading from "@/components/SectionHeading";
import ServicesGrid from "@/components/ServicesGrid";
import ContactCta from "@/components/ContactCta";
import YouTubeShowcase from "@/components/YouTubeShowcase";

const articles = ["Kariyer Seçiminde En Sık Yapılan Hatalar", "Ertelemenin Görünmeyen Sebebi", "Daha İyi Sorular Sormak Neden Önemli?"];
const supportTopics = ["Kaygı ve stres", "Erteleme ve odaklanma", "Travmatik yaşantıların etkileri", "Karar verme", "Kendini tanıma", "Yaşam yönü", "Kariyer geçişleri"];
const trustPoints = [
  ["01", "Psikolojik danışmanlık temeli", "Yıldız Teknik Üniversitesi Rehberlik ve Psikolojik Danışmanlık eğitiminin üzerine kurulu bir yaklaşım."],
  ["02", "Birey ve kurum deneyimi", "Bireysel gelişim ihtiyaçlarını; kariyer, insan kaynakları ve öğrenme dünyasının gerçekleriyle birlikte ele almak."],
  ["03", "Eğitim ve seminerler", "Farklı kurum, okul ve topluluklarda insan gelişimini anlaşılır ve uygulanabilir hale getiren çalışmalar."],
  ["04", "Veriye dayalı gelişim", "Gelişimi yalnızca hislerle değil; takip, gözlem ve anlamlı sistemlerle görünür kılmaya önem vermek."],
];

export default function Home() { return <PageShell>
  <section className="overflow-hidden"><div className="shell grid min-h-[calc(100svh-73px)] items-center gap-12 py-14 lg:grid-cols-[1.05fr_.95fr] lg:py-20">
    <div><p className="eyebrow">PSİKOLOJİK DANIŞMANLIK · KARİYER · EĞİTİM</p><h1 className="display mt-6 max-w-3xl text-5xl leading-[.96] sm:text-6xl lg:text-7xl">İnsan gelişimi, doğru sorularla başlar.</h1><p className="mt-7 max-w-xl text-lg leading-8 text-slate-600">Kendini anlamak, zorlandığın noktaları fark etmek ve hayatında daha dengeli bir yön kurmak için; psikoloji, kariyer gelişimi ve öğrenme bilimiyle çalışıyorum.</p><div className="mt-9 flex flex-wrap gap-3"><Link href="/iletisim" className="rounded-full bg-[#17324f] px-6 py-3.5 text-sm font-semibold text-white transition hover:bg-[#10283f]">Randevu al</Link><Link href="/egitimler" className="rounded-full border border-[#17324f]/20 px-6 py-3.5 text-sm font-semibold text-[#17324f] transition hover:border-[#17324f]">Eğitimleri incele</Link></div></div>
    <div className="relative mx-auto w-full max-w-md lg:max-w-none"><div className="absolute -inset-4 -z-10 rounded-[3rem] bg-[#e8dfcf]" /><div className="relative aspect-[4/5] overflow-hidden rounded-[2.3rem]"><Image src="/sezgin6.jpg" alt="Sezgin İldeş" fill priority sizes="(max-width: 1024px) 90vw, 40vw" className="object-cover object-center" /></div><p className="mt-4 text-right text-xs font-medium tracking-[.14em] text-slate-500">SEZGİN İLDEŞ</p></div>
  </div></section>
  <section className="border-y border-[#17324f]/10 bg-[#efece6]"><div className="shell grid gap-7 py-8 text-[#17324f] sm:grid-cols-3"><div><p className="text-2xl font-semibold">Bireyler</p><p className="mt-1 text-sm text-slate-600">Kendini ve yönünü daha iyi anlamak için.</p></div><div><p className="text-2xl font-semibold">Kurumlar</p><p className="mt-1 text-sm text-slate-600">İnsan odağında gelişim deneyimleri için.</p></div><div><p className="text-2xl font-semibold">Topluluklar</p><p className="mt-1 text-sm text-slate-600">Öğrenme ve düşünme alanları açmak için.</p></div></div></section>
  <section className="shell grid gap-10 py-24 sm:py-32 lg:grid-cols-[.8fr_1.2fr] lg:items-start"><div><p className="eyebrow">BİREYSEL DANIŞMANLIK</p><h2 className="display mt-5 text-4xl leading-tight text-[#17324f] sm:text-5xl">Hangi konularda destek alabilirsiniz?</h2><p className="mt-6 max-w-md text-lg leading-8 text-slate-600">Zorlandığınız noktaları daha iyi anlamak ve hayatınızda uygulanabilir bir yol oluşturmak için birlikte çalışabiliriz.</p><Link href="/iletisim" className="mt-8 inline-block rounded-full bg-[#17324f] px-6 py-3.5 text-sm font-semibold text-white transition hover:bg-[#10283f]">Görüşme talep et</Link></div><div className="grid gap-3 sm:grid-cols-2">{supportTopics.map((topic, index) => <div key={topic} className="rounded-3xl border border-[#17324f]/10 p-6 transition hover:border-[#b99155] hover:bg-[#efece6]"><p className="text-xs font-bold tracking-[.16em] text-[#b99155]">{String(index + 1).padStart(2, "0")}</p><p className="mt-10 text-xl font-semibold text-[#17324f]">{topic}</p></div>)}</div></section>
  <section className="shell py-24 sm:py-32"><SectionHeading eyebrow="ÇALIŞMA ALANLARI" title="İhtiyaca göre şekillenen, insana yakın çalışmalar." intro="Her çalışma; hedefi, bağlamı ve insanı merkeze alan yalın bir süreçle tasarlanır." /><ServicesGrid /></section>
  <section className="bg-[#efece6]"><div className="shell py-24 sm:py-32"><div className="grid gap-10 lg:grid-cols-[.72fr_1.28fr] lg:items-end"><div><p className="eyebrow">NEDEN SEZGİN İLDEŞ?</p><h2 className="display mt-5 text-4xl leading-tight text-[#17324f] sm:text-5xl">Bilimsel temeli, hayatın gerçekliğiyle buluşturmak.</h2><p className="mt-6 max-w-md leading-8 text-slate-600">Amaç yalnızca bir konuyu konuşmak değil; size veya kurumunuza karşılığı olan bir gelişim alanı açmak.</p><Link href="/hakkimda" className="mt-8 inline-block text-sm font-semibold text-[#17324f]">Yaklaşımımı incele →</Link></div><div className="grid gap-4 sm:grid-cols-2">{trustPoints.map(([number, title, text]) => <article key={number} className="rounded-3xl bg-[#f8f7f4] p-7"><p className="text-xs font-bold tracking-[.16em] text-[#b99155]">{number}</p><h3 className="mt-10 text-xl font-semibold text-[#17324f]">{title}</h3><p className="mt-4 leading-7 text-slate-600">{text}</p></article>)}</div></div></div></section>
  <section className="bg-[#17324f] text-white"><div className="shell grid gap-12 py-24 sm:py-32 lg:grid-cols-[.8fr_1.2fr]"><div><p className="eyebrow text-[#d9c49f]">YAKLAŞIM</p><h2 className="mt-5 font-serif text-4xl leading-tight sm:text-5xl">Bilgi, ancak hayata değdiğinde dönüşür.</h2></div><div className="space-y-6 text-lg leading-8 text-slate-200"><p>Psikolojik danışmanlıktan kariyer gelişimine, eğitim tasarımından kurum çalışmalarına uzanan deneyimimi tek bir amaç için kullanıyorum: insan gelişimini görünür ve uygulanabilir kılmak.</p><p>İyi bir gelişim sürecinin doğru cevaplardan önce doğru sorularla başladığına inanıyorum.</p><Link className="inline-block border-b border-[#d9c49f] pb-1 text-sm font-semibold text-[#d9c49f]" href="/hakkimda">Hakkımda daha fazlası →</Link></div></div></section>
  <section className="shell py-24 sm:py-32"><div className="flex flex-col gap-8 sm:flex-row sm:items-end sm:justify-between"><SectionHeading eyebrow="YAZILAR" title="Düşünmek için küçük bir alan." intro="Psikoloji, kariyer ve öğrenme üzerine notlar." /><Link href="/blog" className="text-sm font-semibold text-[#17324f]">Tüm yazılar →</Link></div><div className="mt-10 grid gap-4 md:grid-cols-3">{articles.map((article, i) => <Link href="/blog" className="group rounded-3xl border border-[#17324f]/10 p-7 transition hover:border-[#b99155] hover:bg-[#efece6]" key={article}><p className="text-xs font-bold tracking-[.15em] text-[#b99155]">{String(i+1).padStart(2,"0")} · YAKINDA</p><h3 className="mt-16 text-2xl font-semibold leading-tight text-[#17324f]">{article}</h3><p className="mt-5 text-sm font-semibold text-[#17324f]">Oku →</p></Link>)}</div></section>
  <YouTubeShowcase />
  <ContactCta />
</PageShell>; }
